import test from 'node:test';
import assert from 'node:assert/strict';
import {makePartials,generateSamples,spectrum,validateSound,wavBuffer,activePartials} from '../dist/dsp.js';
const sound=(preset='sine',frequency=375)=>({fundamental:frequency,harmonic:true,preset,partials:makePartials(9,preset,frequency)});
test('FFT locates known tone at the correct bin',()=>{const s=sound(),freq=spectrum(generateSamples(s,8192,48000));let peak=1;for(let i=2;i<freq.length;i++)if(freq[i]>freq[peak])peak=i;assert.equal(peak,64);assert.ok(Math.abs(freq[peak]-20*Math.log10(.21))<.01);});
test('waveform presets and normalization',()=>{for(const preset of ['sine','saw','triangle','square']){const s=sound(preset),values=generateSamples(s,48000);assert.ok(Math.max(...values)<=1);assert.ok(Math.min(...values)>=-1);if(preset==='square'||preset==='triangle')assert.equal(s.partials[1].a,0);}assert.equal(sound('triangle').partials[2].p,180);});
test('mute, solo, Nyquist exclusion',()=>{const s=sound('saw');s.partials[0].solo=true;s.partials[1].mute=true;assert.equal(activePartials(s).filter(p=>p.a).length,1);s.partials[0].mute=true;assert.ok(generateSamples(s,1024).every(x=>x===0));const high=sound('saw',4000);assert.ok(activePartials(high).every(p=>p.f<24000));});
test('two nearby frequencies produce beating',()=>{const s=sound();s.harmonic=false;s.partials[0].f=220;s.partials[1]={a:1,f:222,p:0};const a=generateSamples(s,48000);const rms=(start)=>Math.sqrt(a.slice(start,start+480).reduce((sum,x)=>sum+x*x,0)/480);assert.ok(rms(0)>rms(12000)*10);});
test('shared input is bounded and malformed sound rejected',()=>{assert.throws(()=>validateSound({partials:[]}));assert.throws(()=>validateSound({partials:Array(33).fill({})}));const s=validateSound({fundamental:99999,partials:[{a:99,f:-100,p:999}]});assert.equal(s.fundamental,20000);assert.deepEqual(s.partials[0],{a:1,f:1,p:180,mute:false,solo:false});});
test('WAV export uses valid PCM header and length',()=>{const wav=wavBuffer(new Float32Array([0,1,-1]));const v=new DataView(wav);assert.equal(wav.byteLength,50);assert.equal(v.getUint32(24,true),48000);assert.equal(v.getUint32(40,true),6);assert.equal(v.getInt16(46,true),32767);assert.equal(v.getInt16(48,true),-32768);});
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
test('audio worklet preserves prescribed phase relationships after crossfade',()=>{let Processor;const sandbox={AudioWorkletProcessor:class{constructor(){this.port={};}},sampleRate:48000,Math,registerProcessor:(name,p)=>Processor=p};vm.runInNewContext(readFileSync(new URL('../dist/synth-worklet.js',import.meta.url),'utf8'),sandbox);const instance=new Processor(),s=sound('triangle',375),parts=activePartials(s);const norm=1/Math.max(1,parts.reduce((a,p)=>a+p.a,0));instance.port.onmessage({data:{type:'configure',partials:parts,norm}});const output=new Float32Array(4096);instance.process([],[[output]]);const expected=generateSamples(s,4096);for(let i=1300;i<4096;i++)assert.ok(Math.abs(output[i]-expected[i])<1e-6);});
test('20 kHz survives sound sharing and synthesis without aliased overtones',()=>{const s=validateSound(JSON.parse(JSON.stringify(sound('saw',20000))));assert.equal(s.fundamental,20000);for(const rate of [44100,48000]){assert.deepEqual(activePartials(s,rate).map(p=>p.f),[20000]);const bins=spectrum(generateSamples(s,8192,rate));let peak=1;for(let i=2;i<bins.length;i++)if(bins[i]>bins[peak])peak=i;assert.ok(Math.abs(peak*rate/8192-20000)<=rate/8192);}});

test('frozen display redraws once per invalidation and resumes live collection',()=>{const source=readFileSync(new URL('../dist/app.js',import.meta.url),'utf8');const paint=source.slice(source.indexOf('function paint(now)'),source.indexOf('const clock='));let draws=0,collections=0;const state={requestAnimationFrame(){},document:{hidden:false},lastPaint:0,dirty:true,frozen:true,playing:true,latest:{},lastSpectro:0,source:'synth',drawWave(){draws++},drawSpectrum(){},drawSpectrogram(){},collect(){collections++;return {};}};vm.createContext(state);vm.runInContext(paint+';paint(100);paint(200);paint(300)',state);assert.equal(draws,1);assert.equal(collections,0);state.dirty=true;vm.runInContext('paint(400);paint(500)',state);assert.equal(draws,2);state.frozen=false;vm.runInContext('paint(600);paint(700)',state);assert.equal(collections,2);assert.equal(draws,4);});

const worklet=()=>{let Processor;const sandbox={AudioWorkletProcessor:class{constructor(){this.port={};}},sampleRate:48000,Math,registerProcessor:(name,p)=>Processor=p};vm.runInNewContext(readFileSync(new URL('../dist/synth-worklet.js',import.meta.url),'utf8'),sandbox);return new Processor();};
const configure=(w,s)=>{const parts=activePartials(s);w.port.onmessage({data:{type:'configure',partials:parts,norm:1/Math.max(1,parts.reduce((a,p)=>a+p.a,0)),fundamental:s.harmonic?s.fundamental:0}});};
test('worklet keeps harmonic phase relationships with a shared fundamental phase',()=>{const w=worklet(),s=sound('triangle',375);configure(w,s);const out=new Float32Array(4096);w.process([],[[out]]);const expected=generateSamples(s,4096);for(let i=1300;i<4096;i++)assert.ok(Math.abs(out[i]-expected[i])<1e-6);});
test('reconfiguring while playing stays continuous (no crossfade dip or click)',()=>{for(const harmonic of [true,false]){const w=worklet(),s=sound('saw',220);s.harmonic=harmonic;configure(w,s);const warm=new Float32Array(2000),a=new Float32Array(1000),b=new Float32Array(3000);w.process([],[[warm]]);w.process([],[[a]]);s.partials[0].a=.8;s.partials[2].a=.5;configure(w,s);w.process([],[[b]]);const all=[...a,...b];let jump=0;for(let i=1;i<all.length;i++)jump=Math.max(jump,Math.abs(all[i]-all[i-1]));assert.ok(jump<.15,`harmonic=${harmonic} jump ${jump}`);const rms=x=>Math.sqrt(x.reduce((q,v)=>q+v*v,0)/x.length);const steady=rms(b.slice(2000));for(let i=0;i<1200;i+=218)assert.ok(rms(b.slice(i,i+218))>steady*.9,`harmonic=${harmonic}: level dip during crossfade`);}});
